---
- name: Create VictoriaMetrics system group
  group:
    name: "{{ victoriametrics_system_group }}"
    state: present
    system: true
  when: victoriametrics_system_group != "root"

- name: Create VictoriaMetrics system user
  user:
    name: "{{ victoriametrics_system_user }}"
    groups: "{{ victoriametrics_system_group }}"
    append: true
    shell: /usr/sbin/nologin
    system: true
    createhome: false
  when: victoriametrics_system_user != "root"

- name: Ensure existense of /usr/local/bin
  file:
    path: /usr/local/bin
    state: directory
    mode: 0755

- name: Ensure existense of VictoriaMetrics storage directory
  file:
    path: "{{ victoriametrics_data_dir }}"
    state: directory
    mode: 0755
    owner: "{{ victoriametrics_system_user }}"
    group: "{{ victoriametrics_system_group }}"

- when: victoriametrics_install_standalone|bool
  block:
    - name: Delete existing VictoriaMetrics version if it's different.
      file:
        path: /usr/local/bin/victoria-metrics-prod
        state: absent
      when:  victoriametrics_binary.stat.exists|bool and
             victoriametrics_version not in victoriametrics_installed_version.stderr

    - name: Download and unarchive VictoriaMetrics release binary
      unarchive:
        src: "{{ victoriametrics_download_url }}"
        dest: /usr/local/bin
        mode: 0751
        owner: "{{ victoriametrics_system_user }}"
        group: "{{ victoriametrics_system_group }}"
        remote_src: yes
      notify: Restart VictoriaMetrics service
      when:
        - not ansible_check_mode
        - victoriametrics_binary.stat.exists|bool or
          victoriametrics_version not in victoriametrics_installed_version.stderr

- when: victoriametrics_install_vmutils|bool
  block:
    - name: Delete existing vmutils version if it's different.
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - vmagent-prod
        - vmalert-prod
        - vmauth-prod
        - vmbackup-prod
        - vmctl-prod
        - vmrestore-prod
      when:  vmutils_binary.stat.exists|bool and
             victoriametrics_vmutils_version not in vmutils_installed_version.stderr

    - name: Download and unarchive vmutils release binary
      unarchive:
        src: "{{ victoriametrics_vmutils_url }}"
        dest: /usr/local/bin
        mode: 0751
        owner: "{{ victoriametrics_system_user }}"
        group: "{{ victoriametrics_system_group }}"
        remote_src: yes
      when:
        - not ansible_check_mode
        - vmutils_binary.stat.exists|bool or
          victoriametrics_vmutils_version not in vmutils_installed_version.stderr
