---
# Add systemd options
- name: Assert usage of systemd as an init system
  assert:
    that: ansible_service_mgr == 'systemd'
    msg: "This role only works with systemd"

- name: Get systemd version
  command: systemd --version
  changed_when: false
  check_mode: false
  register: __systemd_version

- name: Set systemd version fact
  set_fact:
    victoriametrics_systemd_version: "{{ __systemd_version.stdout_lines[0].split(' ')[-1] }}"

# Victoriametrics version
- name: Check if VictoriaMetrics is installed
  stat:
    path: /usr/local/bin/victoria-metrics-prod
  changed_when: false
  check_mode: false
  register: victoriametrics_binary

- name: Check current VictoriaMetrics version
  command: /usr/local/bin/victoria-metrics-prod --version
  changed_when: false
  failed_when: false
  check_mode: false
  register: victoriametrics_installed_version
  when: victoriametrics_binary.stat.exists|bool

# Victoriametrics utils version
- name: Check if vmutils are installed
  stat:
    path: /usr/local/bin/vmctl-prod
  changed_when: false
  check_mode: false
  register: vmutils_binary

- name: Check current vmutils version
  command: /usr/local/bin/vmctl-prod --version
  changed_when: false
  failed_when: false
  check_mode: false
  register: vmutils_installed_version
  when: vmutils_binary.stat.exists|bool
