---
- name: Restart VictoriaMetrics service
  systemd:
    daemon_reload: true
    name: victoriametrics
    state: restarted

- name: Restart vminsert service
  systemd:
    daemon_reload: true
    name: vminsert
    state: restarted

- name: Restart vmselect service
  systemd:
    daemon_reload: true
    name: vmselect
    state: restarted

- name: Restart vmstorage service
  systemd:
    daemon_reload: true
    name: vmstorage
    state: restarted
